version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

  flask-app:
    image: flask-app:latest  
    ports:
      - '5000:5000'
    depends_on:
      - mongodb

volumes:
  dbdata6:

