version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      DATABASE_NAME: your_database

  mongodb:
    image: mongo
    ports:
      - "${MONGO_PORT:-27017}:${MONGO_PORT:-27017}"
