version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
