apiVersion: v1
kind: Service
metadata:
  name: webdb-service
  namespace: maktoumg
spec:
  selector:
    app: webdb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort

